name: Build and Deploy to Azure

env:
  AZURE_CONTAINER_REGISTRY_NAME: "captainborisdemoacr"  # set this to the name of your Azure Container Registry
  AZURE_CONTAINER_REGISTRY: "captainborisdemoacr.azurecr.io"
  CONTAINER_NAME: "hello-world"
  RESOURCE_GROUP: "github-actions-rg"
  CLUSTER_NAME: "captainboris-cicd-aks"
  DEPLOYMENT_MANIFEST_PATH: "kubernetes"

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildImage:
    runs-on: Ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
          # Container registry password
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          # Container registry server url
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
           
      - name: Build Docker Image and push it to Azure Container Registry
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          file: ./Dockerfile

  deploy: 
    runs-on: ubuntu-latest
    permissions: 
      actions: read
      contents: read
      id-token: write


    environment: Production
    needs: [buildImage]

    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: Azure/login@v1.5.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1.2
        with:
          kubelogin-version: 'v0.0.25'
  
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: envsubst-action
        # You may pin to the exact commit or the version.
        # uses: danielr1996/envsubst-action@704434f349d6cf73fe52e977d59375ba2fb97232
        uses: danielr1996/envsubst-action@1.1.0
        env: 
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AZURE_CONTAINER_REGISTRY_NAME: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
          AZURE_CONTAINER_REGISTRY: ${{ env.AZURE_CONTAINER_REGISTRY }}
        with:
          # File to run substitutions on
          input: 
            ${{ env.DEPLOYMENT_MANIFEST_PATH }}/hello-world-deployment.yaml
          # File to write result to
          output: 
            hello-world-deployment.yaml

              
 
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            ${{ env.DEPLOYMENT_MANIFEST_PATH }}/hello-world-service.yaml
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
